gate_ratios:
  proprioception_ratio: 1.0
  navigation_ratio: 0.0
  terrain_ratio: 0.0
  passion_ratio: 0.0

unity_params:
  joint:
    target_smoothing: 0.2

  reward:
    survival_reward: 1.6
    stay_success_reward: 5.0
    staying_reward: 1.0
    stay_success_threshold: 5.0
    distance_penalty_multiplier: 0.1
    jitter_penalty_multiplier: 0.2
    energy_penalty_multiplier: 0.005
    upright_reward_multiplier: 0.5
    height_match_reward_multiplier: 0.25
    direction_reward_multiplier: 0.5
