policy_kwargs:
  features_extractor_class: train.extractors.features_extractor.FeaturesExtractor
  features_extractor_kwargs:
    proprioception_kwargs:
      hidden_dims: [256, 256, 128]

    navigation_kwargs:
      max_tokens: 3

      d_model: 16
      num_layers: 1
      nhead: 2

    terrain_kwargs:
      resolution: 8
      hidden_dims: [128, 64, 32]

    gate_ratios:
      proprioception_ratio: 1.0
      navigation_ratio: 0.0
      terrain_ratio: 0.0
      passion_ratio: 0.0

  net_arch:
    pi: [256, 256]
    qf: [512, 512]

unity_params:
  navigation:
    max_tokens: ${model.policy_kwargs.features_extractor_kwargs.navigation_kwargs.max_tokens}

  terrain:
    resolution: ${model.policy_kwargs.features_extractor_kwargs.terrain_kwargs.resolution}

  joint:
    target_smoothing: 0.2

  reward:
    survival_reward: 1.6
    stay_success_reward: 0.0
    staying_reward: 0.0
    stay_success_threshold: 0.0
    distance_penalty_multiplier: 0.0
    jitter_penalty_multiplier: 0.2
    energy_penalty_multiplier: 0.005
    upright_reward_multiplier: 0.5
    height_match_reward_multiplier: 0.25
    direction_reward_multiplier: 0.0

  normalization:
    expected_max_speed: 5.0
    expected_max_distance: 10.0
    expected_max_thickness: 1.0
    expected_max_height: 2.0
    expected_max_force: 300.0
