policy_kwargs:
  features_extractor_class: train.extractors.feature_extractor.FeatureExtractor
  features_extractor_kwargs:
    proprioception_kwargs:
      hidden_dims: [256, 256, 128]

    navigation_kwargs:
      max_token: 3

      d_model: 16
      num_layers: 1
      nhead: 2

    terrain_kwargs:
      resolution: 8
      hidden_dims: [128, 64, 32]

  net_arch:
    pi: [256, 256]
    qf: [512, 512]

normalization:
  expected_max_speed: 5.0
  expected_max_distance: 10.0
  expected_max_thickness: 1.0
  expected_max_height: 2.0
  expected_max_force: 300.0
