policy_kwargs:
  features_extractor_class: train.extractors.feature_extractor.FeatureExtractor
  features_extractor_kwargs:
    navigation_kwargs:
      d_model: 16
      num_layers: 1
      max_token: 3
      nhead: 2
    proprioception_kwargs:
      hidden_dims: [256, 256, 128]
    terrain_kwargs:
      hidden_dims: [128, 64, 32]
  net_arch:
    pi: [256, 256]
    qf: [512, 512]

unity_kwargs:
  navigation_sensor__max_token: 3
  terrain__resolution: 8
